version: '3'

services:
  golab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - PORT=8080
